import type { NodeCategory, NodeData } from "@/lib/types";

export type NodeKindMeta = {
  category: NodeCategory;
  label: string;
  shortLabel: string;
  badge: string;
  color: string;
  description: string;
  defaultLabel: string;
  defaultData: () => NodeData;
};

export const NODE_KINDS: Record<NodeCategory, NodeKindMeta> = {
  input: {
    category: "input",
    label: "Start",
    shortLabel: "Start",
    badge: "START",
    color: "#2e7d4f",
    description: "Entry point — exactly one per rule. The request enters here.",
    defaultLabel: "Start",
    defaultData: () => ({ label: "Start", category: "input" }),
  },
  output: {
    category: "output",
    label: "End",
    shortLabel: "End",
    badge: "END",
    color: "#5b3a72",
    description: "Exit point — assembles the envelope's result.",
    defaultLabel: "End",
    defaultData: () => ({ label: "End", category: "output" }),
  },
  filter: {
    category: "filter",
    label: "Filter",
    shortLabel: "Filter",
    badge: "FLT",
    color: "#1f4a6b",
    description: "Predicate over a value. Routes via pass/fail/skip.",
    defaultLabel: "Filter",
    defaultData: () => ({
      label: "Filter",
      category: "filter",
      templateId: "sys-filter-str",
      config: {
        source: { kind: "request", path: "" },
        compare: { operator: "equals", value: "", caseInsensitive: true, trim: true },
        arraySelector: "first",
        onMissing: "fail",
      },
    }),
  },
  logic: {
    category: "logic",
    label: "Logic",
    shortLabel: "Logic",
    badge: "LOG",
    color: "#5b3a72",
    description: "Combine upstream verdicts: and/or/xor/not.",
    defaultLabel: "AND",
    defaultData: () => ({ label: "AND", category: "logic", templateId: "sys-and" }),
  },
  product: {
    category: "product",
    label: "Product",
    shortLabel: "Product",
    badge: "PRD",
    color: "#1c5c3b",
    description: "Emit a structured object (e.g. an ancillary).",
    defaultLabel: "Product",
    defaultData: () => ({
      label: "Product",
      category: "product",
      config: { output: {} },
    }),
  },
  mutator: {
    category: "mutator",
    label: "Mutator",
    shortLabel: "Mutator",
    badge: "MUT",
    color: "#8a5a00",
    description: "Override one field on the upstream object.",
    defaultLabel: "Set field",
    defaultData: () => ({
      label: "Set field",
      category: "mutator",
      templateId: "sys-set",
      config: { target: "", from: "" },
    }),
  },
  calc: {
    category: "calc",
    label: "Calc",
    shortLabel: "Calc",
    badge: "CALC",
    color: "#6b3a1f",
    description: "Arithmetic / boolean expression via NCalc.",
    defaultLabel: "Calc",
    defaultData: () => ({ label: "Calc", category: "calc", config: { expression: "" } }),
  },
  constant: {
    category: "constant",
    label: "Constant",
    shortLabel: "Constant",
    badge: "CON",
    color: "#3a3a3a",
    description: "Emit a literal value.",
    defaultLabel: "Constant",
    defaultData: () => ({ label: "Constant", category: "constant", config: { value: {} } }),
  },
  ruleRef: {
    category: "ruleRef",
    label: "Sub-rule",
    shortLabel: "Sub-rule",
    badge: "REF",
    color: "#444",
    description: "Invoke another rule with mappings.",
    defaultLabel: "Sub-rule",
    defaultData: () => ({
      label: "Sub-rule",
      category: "ruleRef",
      subRuleCall: {
        ruleId: "",
        inputMapping: {},
        outputMapping: {},
        onError: "fail",
        pinnedVersion: "latest",
      },
    }),
  },
  iterator: {
    category: "iterator",
    label: "ForEach",
    shortLabel: "ForEach",
    badge: "ITR",
    color: "#0f5b66",
    description: "Iterate over an array; downstream sub-graph runs per element.",
    defaultLabel: "For each",
    defaultData: () => ({
      label: "For each",
      category: "iterator",
      config: { source: "", as: "item" },
    }),
  },
  merge: {
    category: "merge",
    label: "Merge",
    shortLabel: "Merge",
    badge: "MRG",
    color: "#0f5b66",
    description: "Close iteration scope and aggregate per-iteration outputs.",
    defaultLabel: "Merge",
    defaultData: () => ({ label: "Merge", category: "merge", config: { mode: "collect" } }),
  },
  reference: {
    category: "reference",
    label: "Reference",
    shortLabel: "Reference",
    badge: "REF",
    color: "#5b3a72",
    description: "Reference set lookup (read-only, multi-row).",
    defaultLabel: "Reference",
    defaultData: () => ({ label: "Reference", category: "reference" }),
  },
  api: {
    category: "api",
    label: "API",
    shortLabel: "API",
    badge: "API",
    color: "#1f4a6b",
    description: "Outbound HTTP callout. Mandatory timeoutMs.",
    defaultLabel: "Call API",
    defaultData: () => ({
      label: "Call API",
      category: "api",
      config: { url: "", method: "GET", timeoutMs: 5000 },
    }),
  },
  switch: {
    category: "switch",
    label: "Switch",
    shortLabel: "Switch",
    badge: "SWITCH",
    color: "#5b3a72",
    description: "N-way branch — emits the matched case name.",
    defaultLabel: "Switch",
    defaultData: () => ({
      label: "Switch",
      category: "switch",
      config: { input: "", cases: [] },
    }),
  },
  assert: {
    category: "assert",
    label: "Assert",
    shortLabel: "Assert",
    badge: "ASSERT",
    color: "#b3261e",
    description: "Runtime invariant — fail the rule when condition is falsy.",
    defaultLabel: "Assert",
    defaultData: () => ({
      label: "Assert",
      category: "assert",
      config: { condition: "" },
    }),
  },
  bucket: {
    category: "bucket",
    label: "Bucket",
    shortLabel: "Bucket",
    badge: "BUCKET",
    color: "#1f4a6b",
    description: "Sticky-hash A/B assignment — same key, same bucket.",
    defaultLabel: "Bucket",
    defaultData: () => ({
      label: "Bucket",
      category: "bucket",
      config: { hashKey: "", buckets: [] },
    }),
  },
  sort: {
    category: "sort",
    label: "Sort",
    shortLabel: "Sort",
    badge: "SORT",
    color: "#3a3a3a",
    description: "Stable sort of the upstream array.",
    defaultLabel: "Sort",
    defaultData: () => ({
      label: "Sort",
      category: "sort",
      config: { direction: "asc", nulls: "last" },
    }),
  },
  limit: {
    category: "limit",
    label: "Limit",
    shortLabel: "Limit",
    badge: "LIM",
    color: "#3a3a3a",
    description: "Take N elements after optional offset.",
    defaultLabel: "Limit",
    defaultData: () => ({
      label: "Limit",
      category: "limit",
      config: { count: 10, offset: 0 },
    }),
  },
  distinct: {
    category: "distinct",
    label: "Distinct",
    shortLabel: "Distinct",
    badge: "DIST",
    color: "#3a3a3a",
    description: "Dedupe array by key (or whole element).",
    defaultLabel: "Distinct",
    defaultData: () => ({
      label: "Distinct",
      category: "distinct",
      config: { keep: "first" },
    }),
  },
  groupBy: {
    category: "groupBy",
    label: "Group by",
    shortLabel: "Group",
    badge: "GROUP",
    color: "#3a3a3a",
    description: "Partition array into { key1: [...], key2: [...] }.",
    defaultLabel: "Group by",
    defaultData: () => ({
      label: "Group by",
      category: "groupBy",
      config: { groupKey: "" },
    }),
  },
};

export const PALETTE_CATEGORIES: NodeCategory[] = [
  "filter",
  "logic",
  "product",
  "mutator",
  "calc",
  "constant",
  "iterator",
  "merge",
  "switch",
  "assert",
  "bucket",
  "sort",
  "limit",
  "distinct",
  "groupBy",
  "reference",
  "api",
  "ruleRef",
];
